### ISSUE TITLE
Error upon importing

### ISSUE THREAD

**Issue by fire17** [cj-praveen/googlesearch.py#1]
Hey brother,
This looks like a really nice project if it works, I dont know why seaching google in python is this troublesome.
I like how you give the title as well as the URL, (it would be nice to get description too)

Anyways im getting an error when importing,
Hope you fix the problem,
Thanks a lot! and have a good one!

```
>>> import googlesearch_py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/magic/anaconda3/lib/python3.7/site-packages/googlesearch_py.py", line 5, in <module>
    def search(query : str) -> list[dict] | list:
TypeError: 'type' object is not subscriptable
```

**Comment by fire17** [comment]
for you or anyone else, currently my working solution is using
https://github.com/Animenosekai/googlesearch/

good luck to everyone! 👍 :)

**Comment by cj-praveen** [comment]
@fire17 
### Thanks for creating an issue and mentioning your problems.

The error you faced is now fixed.
Now, you can get the website description too.

For more visit [https://pypi.org/project/googlesearch.py/1.6.1/](https://pypi.org/project/googlesearch.py/1.6.1/)

**Comment by cj-praveen** [comment]
@fire17 
However, https://github.com/Animenosekai/googlesearch/ This one is heavy and takes time to return results. It uses BS4 and some web scraping libraries out there.

But **googlesearch.py** is built using [httpx](https://pypi.org/project/httpx/) and built-in libraries, which gives results faster than the one you mentioned. But the choice is yours; do what feels right to you.

**Comment by fire17** [comment]
> But **googlesearch.py** is built using [httpx](https://pypi.org/project/httpx/) and built-in libraries, which gives results faster than the one you mentioned. But the choice is yours; do what feels right to you.

That's super cool to hear!
You should have all the stars man @cj-praveen Great job!!!
⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐ 

I can confirm it's working, will change my imports... Thanks a bunch!
