### ISSUE TITLE
[Feature Request] Get actual contents of search results

### ISSUE THREAD

**Issue by fire17** [cj-praveen/googlesearch.py#2]
Hi there, hope you are well
I know this might be outside of the scope of this package
but since you mentions using httpx , and being a proficient scrapper, i thought you might be up for it
This could make this a really powerful tool

Aside from the title, description and url, I'd like to get the main body of the sites.

For example, I'd like to start experimenting with chatGPT and integrations; see [LangChain](https://github.com/hwchase17/langchain) 
There're some crazy stuff going on there... i found out through:

Idealy I'd like to use
```
def my_filter_foo(full_contents, url):
    # Process full content manually / using a template given the url domain / using ai ;)
    return final_content

googlesearch_py.search(query=myQuery, max_results=3, get_contents=True, scraper_filter= my_filter_foo)
# or 
googlesearch_py.scrape(url=https://en.wikipedia.org/wiki/Programming_language, scraper_filter = my_filter_foo)
```
To get
```
[
    {
        "url": "https://en.wikipedia.org/wiki/Programming_language",
        "title": "Programming language - Wikipedia",
        "description": "A programming language is a system of notation for writing computer programs. ... Most programming languages are text-based formal languages, but they may also be...",
        "contents":"A programming language is a system of notation for writing computer programs.[1] Most programming languages are text-based formal languages, but they may also be graphical. They are a kind of computer language.
The description of a programming language is usually split into the two components of syntax (form) and semantics (meaning), which are usually defined by a formal language. Some languages are defined by a specification document (for example, the C programming language is specified by an ISO Standard) while other languages (such as Perl) have a dominant implementation that is treated as a reference. Some languages have both, with the basic language defined by a standard and extensions taken from the dominant implementation being common.
Programming language theory is the subfield of computer science that studies the design, implementation, analysis, characterization, and classification of programming languages."
    }
]
```

### My answers:
1: add a placeholder filter/process function that we can write, that will get and process all of the contents before
2: (in case no process function was passed) check the url, if the domain is known, apply the known function
  - If you do this, I'll gladly fork and PR to add some useful sites (wikipedia, medium, etc...)

3: if no function or known domain was found, leave it as is, it just might be used by ai and not a human directly, so having all of the site's information might not be bad :)

Hope you realize how useful this could be.
And hope that it's straightforward enough for you to do haha
Thank you very much and have good one! 💛 

PS - Thanks a lot @cj-praveen for fixing the import issue... PLUS you added the description! that's amazing
I can't believe this package is not more well known. much love and thanks to you ⭐

**Comment by fire17** [comment]
@cj-praveen Honestly,
If you just provide us with the 
`site_contents = googlesearch_py.scrape(url)`
and 
`results_with_contents = googlesearch_py.search(promt, get_contents=True)`
That would be more than enough, and we can do the rest :)
much love ❤️

**Comment by fire17** [comment]
hey bro @cj-praveen why do you have to be so fast? haha jk
I hope it wont conflict with your work, but i've made a for and pr to include all of this 
I cant believe how easy it is with httpx :)
submitting soon :)

**Comment by cj-praveen** [comment]
@fire17 Umm, But if we add this thing, it will make the library slow because it needs to get the content of the number of pages. Instead of this, we can add a weather search, an [image search](https://github.com/cj-praveen/googlesearch.py/issues/4), and some other features. What do you say?

<img width="200" src="https://user-images.githubusercontent.com/80583308/213897868-3ec06133-1454-4f23-b883-3f608231bebd.jpeg" />

**Comment by fire17** [comment]
Again I really need the contents, even if they take a while longer. I know adding get_contents will take more time , that's why I added the max_results. And also the scrape func independently.
I think it's ok because it is not changing any of the default behavior. 

So please accept the pr 🙏

In other matters, YES I would love for an age search , an weather search is also good even though I'd rather it work when searching , not specifically when searching_weather. I think if you find the url to be of a familiar type, like a weather request or images search etc , the. You can run it through a function that will add more meta fields to the results, like "contents" , "weather", "images", lyrics, etc etc

**Comment by cj-praveen** [comment]
@fire17 Ok, checking your code and soon i'll merge. :)
